name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: progress
  var2: testing
  var3: build
  var4: deploy
  

  
stages:
- stage: Build
  jobs:
  - job: myjob1
    steps:
    - script: echo $(var3) is in $(var1)

- stage: Test
  jobs:
  - job: myjob2
    steps:
    - script: echo $(var2) is in $(var1)
  - job: myjob3
    displayName: My First Job
    steps:
    - script: echos $(var2) completed
    continueOnError: true
    workspace:
      clean: outputs
  dependsOn: []

- stage: Deploy
  jobs:
  - job: myjob4
    steps:
    - script: echo $(var4) is in $(var1)
/*
- stage: Container
  resources:
    containers:
    - container: linux # reusable alias
      image: ubuntu:16.04
  jobs:
  - job: a
    container: linux # reference
  - job: b
    container: linux # reference 
 */
